spring:
  main:
    web-application-type: NONE

  batch:
    job.names: ${job.name:NONE}
    jdbc:
      initialize-schema: always

slack:
  url: https://slack.com/api
  channel: {{SLACK_CHANNEL}}
  key: {{SLACK_KEY}}
  bot-code: {{SLACK_BOTCODE}}
  write:
    channel-name: {{SLACK_WRITE_CHANNELNAME}}
    text: {{SLACK_WRITE_TEXT}}
