spring:
  main:
    web-application-type: NONE

  batch:
    job.names: ${job.name:NONE}
    jdbc:
      initialize-schema: always

slack:
  url: https://slack.com/api
  channel: your-channel-key-ex-C04T4M4GD11
  key: your-key-prefix-xoxb
  botCode: your-bot-code-ex-U04SY9SHTH9
  write:
    channelName: your-channel-name-ex-SOME-MY-CHANNEL
    text: reply-comment-ex-HELLO-WORLD
