spring:
  main:
    web-application-type: NONE

  batch:
    job.names: ${job.name:NONE}
    jdbc:
      initialize-schema: always

slack:
  url: https://slack.com/api
  channel: ${ secrets.SLACK_CHANNEL }
  key: ${ secrets.SLACK_KEY }
  botCode: ${ secrets.SLACK_BOTCODE }
  write:
    channelName: ${ secrets.SLACK_WRITE_CHANNELNAME }
    text: ${ secrets.SLACK_WRITE_TEXT }
