spring:
  main:
    web-application-type: NONE

  batch:
    job.names: ${job.name:NONE}
    jdbc:
      initialize-schema: always

slack:
  url: https://slack.com/api
  channel: insert-your-channel-code
  key: insert-your-slack-key
  botCode: insert-your-bot-code
  historyRange: insert-your-range
  write:
    channelName: insert-your-channel-name
    text: insert-your-text
