name: Slack Auto Reply Job

# on:
  # schedule:
    # - cron: '*/5 * * * *'
    
jobs:
  gradle:
    strategy:
      matrix:
        os: [ubuntu-latest]
        
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 17
        
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
      
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Make Jar
      env:
        slack_channel: ${{ secrets.SLACK_CHANNEL }}
        slack_key: ${{ secrets.SLACK_KEY }}
        slack_botcode: ${{ secrets.SLACK_BOTCODE }}
        slack_write_channelname: ${{ secrets.SLACK_WRITE_CHANNELNAME }}
        slack_write_text: ${{ secrets.SLACK_WRITE_TEXT }}
      run: ./gradlew bootJar
      
    - name: autoReplyJob Execute
      run: java -jar -Dspring.batch.job.names=autoReplyJob -Dspring.profiles.active=default ./build/libs/action-0.0.1-SNAPSHOT.jar
