name: Slack Auto Reply Job

on:
  workflow_dispatch:
    inputs:
      message:
        description: 'run trigger'
        required: true
    
jobs:
  run-container:
    strategy:
      matrix:
        os: [ubuntu-latest]
        
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    
    - name: Run Docker container
      env:
        slack_channel: ${{ secrets.SLACK_CHANNEL }}
        slack_key: ${{ secrets.SLACK_KEY }}
        slack_botcode: ${{ secrets.SLACK_BOTCODE }}
        slack_write_channelname: ${{ secrets.SLACK_WRITE_CHANNELNAME }}
        slack_write_text: ${{ secrets.SLACK_WRITE_TEXT }}
        SPRING_BATCH_JOB_NAMES: autoReplyJob
      uses: docker://gudrb963/slack-auto-reply:latest
