name: Slack Auto Reply Job

on:
  workflow_dispatch:
    inputs:
      message:
        description: 'run trigger'
        required: true
    
jobs:
  run-container:
    strategy:
      matrix:
        os: [ubuntu-latest]
        
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    
    - name: Run Docker container
      uses: docker://gudrb963/slack-auto-reply:latest
      env:
        SPRING_BATCH_JOB_NAMES: autoReplyJob
