name: Slack Auto Reply Job

on:
  workflow_dispatch:
    inputs:
      message:
        description: 'run trigger'
        default: 'true'
        required: true
    
jobs:
  run-container:
    strategy:
      matrix:
        os: [ubuntu-latest]
        
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    
    - name: Run Docker container
      uses: docker://gudrb963/slack-auto-reply:latest
      env:
        SPRING_BATCH_JOB_NAMES: autoReplyJob
        SLACK_CHANNEL: ${{ secrets.SLACK_CHANNEL }}
        SLACK_KEY: ${{ secrets.SLACK_KEY }}
        SLACK_BOTCODE: ${{ secrets.SLACK_BOTCODE }}
        SLACK_WRITE_CHANNELNAME: ${{ secrets.SLACK_WRITE_CHANNELNAME }}
        SLACK_WRITE_TEXT: ${{ secrets.SLACK_WRITE_TEXT }}
