name: Slack Auto Reply Job

on:
  workflow_dispatch:
    inputs:
      message:
        description: 'run trigger'
        required: true
    
jobs:
  gradle:
    strategy:
      matrix:
        os: [ubuntu-latest]
        
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
        
    - name: Run Docker Container
      uses: docker/metadata-action@v3
      with:
        images: gudrb963/slack-auto-reply:latest
        options: -e SPRING_BATCH_JOB_NAMES=autoReplyJob -e slack_channel=${{ secrets.SLACK_CHANNEL }} -e slack_key=${{ secrets.SLACK_KEY }} -e slack_botcode=${{ secrets.SLACK_BOTCODE }} -e slack_write_channelname=${{ secrets.SLACK_WRITE_CHANNELNAME }} -e slack_write_text=${{ secrets.SLACK_WRITE_TEXT }}
        entrypoint: java -jar /path/to/your/jar/reply-0.0.1-SNAPSHOT.jar --spring.batch.job.names=autoReplyJob
