name: Run Gradle on PRs

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
jobs:
  gradle:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 17
        
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
      
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    
    - name: Execute Gradle build
      run: ./gradlew build
      
  jib:
    needs: gradle
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 17
        
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
      
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Execute Gradle build
      env:
        slack_channel: ${{ secrets.SLACK_CHANNEL }}
        slack_key: ${{ secrets.SLACK_KEY }}
        slack_botcode: ${{ secrets.SLACK_BOTCODE }}
        slack_write_channelname: ${{ secrets.SLACK_WRITE_CHANNELNAME }}
        slack_write_text: ${{ secrets.SLACK_WRITE_TEXT }}
      run: ./gradlew build
        
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Gradle Jib
      run: ./gradlew jib
